"use client";
import React from "react";
import {
  Award,
  BadgeCheck,
  Boxes,
  Briefcase,
  Building,
  Building2,
  CheckCircle2,
  Clock,
  Crown,
  Eye,
  Factory,
  FileSearch,
  Flag,
  Gem,
  Globe,
  GraduationCap,
  Handshake,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  IndianRupee,
  Layers,
  Leaf,
  Lightbulb,
  MapPin,
  Maximize,
  Megaphone,
  Package,
  PackageCheck,
  Palette,
  PartyPopper,
  Printer,
  Quote,
  Recycle,
  Rocket,
  Settings,
  ShieldCheck,
  Shirt,
  ShoppingCart,
  Sparkles,
  Sprout,
  Star,
  Store,
  Target,
  ThumbsUp,
  TrendingUp,
  Trophy,
  Truck,
  Users,
  UtensilsCrossed,
  Zap,
  type LucideIcon,
} from "lucide-react";

// Curated icon map shared with the admin CMS icon picker.
// Keep names in sync with Admin/src/app/about-page/sections.config.tsx (ICON_OPTIONS).
export const ICON_MAP: Record<string, LucideIcon> = {
  Award,
  BadgeCheck,
  Boxes,
  Briefcase,
  Building,
  Building2,
  CheckCircle2,
  Clock,
  Crown,
  Eye,
  Factory,
  FileSearch,
  Flag,
  Gem,
  Globe,
  GraduationCap,
  Handshake,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  IndianRupee,
  Layers,
  Leaf,
  Lightbulb,
  MapPin,
  Maximize,
  Megaphone,
  Package,
  PackageCheck,
  Palette,
  PartyPopper,
  Printer,
  Quote,
  Recycle,
  Rocket,
  Settings,
  ShieldCheck,
  Shirt,
  ShoppingCart,
  Sparkles,
  Sprout,
  Star,
  Store,
  Target,
  ThumbsUp,
  TrendingUp,
  Trophy,
  Truck,
  Users,
  UtensilsCrossed,
  Zap,
};

interface AboutIconProps {
  name?: string | null;
  className?: string;
  size?: number;
  strokeWidth?: number;
}

export default function AboutIcon({ name, className, size, strokeWidth }: AboutIconProps) {
  const Icon = (name && ICON_MAP[name]) || Sparkles;
  return <Icon className={className} size={size} strokeWidth={strokeWidth} aria-hidden="true" />;
}
